# -*- coding: utf-8 -*-
"""LerPOSTGREcomPYTHON.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1joNUsLNrEXB-CJXybaB6TZRVNIAA7aUe

https://www.devmedia.com.br/como-criar-uma-conexao-em-postgresql-com-python/34079

https://www.psycopg.org/docs/

https://pypi.org/project/psycopg2/

# **ELIAS**

https://towardsdatascience.com/sqlalchemy-python-tutorial-79a577141a91
"""

! pip install sqlalchemy

import sqlalchemy as sa
#from sqlalchemy import create_engine

!pip install psycopg2

import psycopg2

# DEFINE UMA FUNCAO PARA ESTABELECER CONEXAO COM BANCO POSTGRES

#pgServer = "10.1.4.109"
#pgDatabase = "dbdw"
#pgUser = "usdw"
#pgPassword = "69lZF@Xq6QE.nqwCV"

MSG_INTRO_PG_CONNECTION = "Intro pg connection"
MSG_SUCCESS_CONNECTION = "Success connection"
MSG_FAIL_CONNECTION = "Fail connection"

def pgEstablishConn(pgUser, pgPassword, pgServer, pgDatabase):
    print(MSG_INTRO_PG_CONNECTION)
    try:
        PG_ENGINE = sa.create_engine(f'postgresql://{pgUser}:{pgPassword}@{pgServer}:5432/{pgDatabase}', encoding="cp1252", pool_size=0, max_overflow=-1, pool_pre_ping=True)
        PG_CONN = psycopg2.connect(host=pgServer, database=pgDatabase, user=pgUser, password=pgPassword)
        print(MSG_SUCCESS_CONNECTION)
    except Exception as e:
        print(MSG_FAIL_CONNECTION)
        print(e)

pgEstablishConn("usdw", "69lZF@Xq6QE.nqwCV", "10.1.4.109", "dbdw")